<?php

namespace Tests\Feature;

use App\Thread;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class ParticipatesInForumTest extends TestCase
{
    use DatabaseMigrations;
    /**
     * @var Thread
     */
    protected $thread;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->thread = factory('App\Thread')->create();
    }

    /** @test */
    public function an_authenticated_user_can_post_a_reply_to_a_thread()
    {
        $this->be($user=factory('App\User')->create());
        $reply = factory('App\Reply')->make();

        $this->post('/threads/'.$this->thread->id.'/reply', $reply->toArray());

        $this->get($this->thread->path())
            ->assertSee($reply->body);
    }

    /** @test */
    public function an_unauthenticated_user_cant_post_a_reply_to_a_thread()
    {
        $this->expectException('Illuminate\Auth\AuthenticationException');
        $this->post('/threads/1/reply', []);
    }
}
