<?php

namespace Tests\Feature;

use Tests\TestCase;
use Illuminate\Foundation\Testing\DatabaseMigrations;

class ReadThreadTest extends TestCase
{
    use DatabaseMigrations;

    protected $thread;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->thread = factory('App\Thread')->create();
    }

    /** @test */
    public function a_user_can_see_all_threads()
    {

        $response = $this->get('/threads');

        $response->assertSee($this->thread->title);
    }

    /** @test */
    public function a_user_can_see_single_thread()
    {

        $response = $this->get('/threads/'.$this->thread->id);

        $response->assertSee($this->thread->title);
    }

    /** @test */
    public function a_user_can_see_replies_to_a_thread()
    {
        $reply = factory('App\Reply')->create(['thread_id'=> $this->thread->id]);
        $response = $this->get('/threads/'.$this->thread->id);

        $response->assertSee($reply->body);
    }
}
