<?php

namespace Tests\Unit;

use App\Thread;
use App\User;
use Illuminate\Support\Collection;
use Tests\TestCase;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class ThreadTest extends TestCase
{
    use DatabaseMigrations;

    /**
     * @var Thread
     */
    protected $thread;

    /**
     * Setup thread
     */
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->thread = factory('App\Thread')->create();

    }

    /** @test */
    public function a_thread_has_replies()
    {
        $replies = factory('App\Reply')->create(['thread_id'=> $this->thread->id]);

        $this->assertInstanceOf(Collection::class, $this->thread->replies);
    }

    /** @test */
    public function a_thread_has_a_creator()
    {
        $this->assertInstanceOf(User::class, $this->thread->creator);
    }

    /** @test */
    public function a_thread_can_add_a_reply()
    {
        $this->thread->addReply([
           'body' => 'FooBar',
           'user_id' => 1,
        ]);

        $this->assertCount(1, $this->thread->replies);
    }
}
